import { Event, Club, Resource } from '@/types';

// Mock Events
export const mockEvents: Event[] = [
  {
    id: '1',
    title: 'Tech Summit 2024',
    description: 'Annual technology summit featuring workshops, hackathons, and keynote speakers from industry leaders. Join us for three days of innovation and learning.',
    coverImage: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&q=80',
    startDate: new Date('2024-03-15'),
    endDate: new Date('2024-03-17'),
    venue: 'Main Auditorium',
    status: 'published',
    organizers: ['tech-club'],
    createdBy: '1',
    budget: { estimated: 50000, approved: 45000, spent: 32000, items: [] },
    maxParticipants: 500,
    registeredParticipants: ['1', '2', '3', '4', '5'],
    tags: ['Technology', 'Hackathon', 'Networking'],
    isMultiDay: true,
    isCollaborative: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '2',
    title: 'Cultural Night',
    description: 'Celebrate diversity with performances, food stalls, and cultural exhibitions from various student groups.',
    coverImage: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800&q=80',
    startDate: new Date('2024-03-20'),
    endDate: new Date('2024-03-20'),
    venue: 'Open Air Theatre',
    status: 'approved',
    organizers: ['cultural-club'],
    createdBy: '2',
    budget: { estimated: 30000, spent: 0, items: [] },
    maxParticipants: 1000,
    registeredParticipants: ['1', '2'],
    tags: ['Culture', 'Music', 'Dance'],
    isMultiDay: false,
    isCollaborative: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '3',
    title: 'AI/ML Workshop Series',
    description: 'Hands-on workshop series covering machine learning fundamentals to advanced deep learning techniques.',
    coverImage: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&q=80',
    startDate: new Date('2024-04-01'),
    endDate: new Date('2024-04-05'),
    venue: 'Computer Lab 101',
    status: 'pending_approval',
    organizers: ['tech-club', 'coding-society'],
    createdBy: '1',
    maxParticipants: 50,
    registeredParticipants: [],
    tags: ['AI', 'Machine Learning', 'Workshop'],
    isMultiDay: true,
    isCollaborative: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '4',
    title: 'Sports Meet 2024',
    description: 'Annual inter-department sports competition featuring various athletic events.',
    coverImage: 'https://images.unsplash.com/photo-1461896836934- voices-of-pride?w=800&q=80',
    startDate: new Date('2024-04-10'),
    endDate: new Date('2024-04-12'),
    venue: 'Sports Complex',
    status: 'draft',
    organizers: ['sports-club'],
    createdBy: '3',
    budget: { estimated: 75000, spent: 0, items: [] },
    maxParticipants: 300,
    registeredParticipants: [],
    tags: ['Sports', 'Competition', 'Athletics'],
    isMultiDay: true,
    isCollaborative: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// Mock Clubs
export const mockClubs: Club[] = [
  {
    id: 'tech-club',
    name: 'Tech Club',
    description: 'Exploring the frontiers of technology through projects, workshops, and competitions. We build innovative solutions and foster tech talent.',
    logo: undefined,
    category: 'technical',
    members: ['1', '2', '3', '4', '5', '6', '7', '8'],
    coordinators: ['1', '2'],
    head: '1',
    createdAt: new Date(),
    isActive: true,
  },
  {
    id: 'cultural-club',
    name: 'Cultural Club',
    description: 'Celebrating diversity through arts, music, dance, and cultural events. Join us in keeping traditions alive.',
    logo: undefined,
    category: 'cultural',
    members: ['2', '3', '4', '5', '6'],
    coordinators: ['2'],
    head: '2',
    createdAt: new Date(),
    isActive: true,
  },
  {
    id: 'coding-society',
    name: 'Coding Society',
    description: 'Competitive programming, hackathons, and coding challenges. Sharpen your skills with fellow programmers.',
    logo: undefined,
    category: 'technical',
    members: ['1', '3', '5', '7', '9', '10'],
    coordinators: ['3'],
    head: '3',
    createdAt: new Date(),
    isActive: true,
  },
  {
    id: 'sports-club',
    name: 'Sports Club',
    description: 'Promoting fitness and sportsmanship through various athletic activities and inter-college competitions.',
    logo: undefined,
    category: 'sports',
    members: ['4', '5', '6', '8', '9'],
    coordinators: ['4'],
    head: '4',
    createdAt: new Date(),
    isActive: true,
  },
  {
    id: 'drama-club',
    name: 'Drama Club',
    description: 'Express yourself through theatrical performances, skits, and dramatic arts. Stage is our canvas.',
    logo: undefined,
    category: 'arts',
    members: ['2', '4', '6', '8'],
    coordinators: ['6'],
    head: '6',
    createdAt: new Date(),
    isActive: true,
  },
  {
    id: 'debate-club',
    name: 'Debate Society',
    description: 'Engage in intellectual discourse, parliamentary debates, and public speaking competitions.',
    logo: undefined,
    category: 'academic',
    members: ['1', '5', '7', '9'],
    coordinators: ['5'],
    head: '5',
    createdAt: new Date(),
    isActive: true,
  },
];

// Mock Resources
export const mockResources: Resource[] = [
  {
    id: '1',
    name: 'Main Auditorium',
    type: 'hall',
    description: 'State-of-the-art auditorium with advanced audio-visual equipment, perfect for large gatherings and performances.',
    location: 'Block A, Ground Floor',
    capacity: 500,
    amenities: ['Projector', 'Sound System', 'AC', 'Stage Lighting', 'Green Room'],
    images: ['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80'],
    isAvailable: true,
    requiresApproval: true,
    createdAt: new Date(),
  },
  {
    id: '2',
    name: 'Computer Lab 101',
    type: 'lab',
    description: 'Modern computer lab equipped with high-performance workstations and programming tools.',
    location: 'Block B, 1st Floor',
    capacity: 50,
    amenities: ['High-spec PCs', 'Projector', 'Whiteboard', 'AC'],
    images: ['https://images.unsplash.com/photo-1606761568499-6d2451b23c66?w=800&q=80'],
    isAvailable: true,
    requiresApproval: false,
    createdAt: new Date(),
  },
  {
    id: '3',
    name: 'Seminar Hall B',
    type: 'room',
    description: 'Medium-sized seminar hall ideal for workshops, presentations, and club meetings.',
    location: 'Block C, 2nd Floor',
    capacity: 100,
    amenities: ['Projector', 'Sound System', 'AC', 'Whiteboard'],
    images: ['https://images.unsplash.com/photo-1517502884422-41eaead166d4?w=800&q=80'],
    isAvailable: false,
    requiresApproval: true,
    createdAt: new Date(),
  },
  {
    id: '4',
    name: 'DSLR Camera Kit',
    type: 'equipment',
    description: 'Professional Canon DSLR camera with multiple lenses and accessories for event photography.',
    location: 'Media Center',
    amenities: ['Camera Body', 'Multiple Lenses', 'Tripod', 'Lighting Kit'],
    images: ['https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&q=80'],
    isAvailable: true,
    requiresApproval: true,
    createdAt: new Date(),
  },
  {
    id: '5',
    name: 'Open Air Theatre',
    type: 'hall',
    description: 'Beautiful outdoor amphitheater for cultural events, concerts, and large gatherings.',
    location: 'Central Campus',
    capacity: 1000,
    amenities: ['Stage', 'Sound System', 'Lighting'],
    images: ['https://images.unsplash.com/photo-1478147427282-58a87a120781?w=800&q=80'],
    isAvailable: true,
    requiresApproval: true,
    createdAt: new Date(),
  },
  {
    id: '6',
    name: 'Conference Room A',
    type: 'room',
    description: 'Executive conference room for formal meetings and small group discussions.',
    location: 'Admin Block, 3rd Floor',
    capacity: 20,
    amenities: ['Video Conferencing', 'Projector', 'AC', 'Whiteboard'],
    images: ['https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80'],
    isAvailable: true,
    requiresApproval: false,
    createdAt: new Date(),
  },
];

// Mock Analytics Data
export const mockAnalyticsData = {
  eventTrends: [
    { month: 'Jan', count: 12 },
    { month: 'Feb', count: 19 },
    { month: 'Mar', count: 15 },
    { month: 'Apr', count: 22 },
    { month: 'May', count: 18 },
    { month: 'Jun', count: 25 },
  ],
  clubActivity: [
    { club: 'Tech Club', events: 8, members: 45 },
    { club: 'Cultural', events: 6, members: 35 },
    { club: 'Sports', events: 10, members: 60 },
    { club: 'Debate', events: 4, members: 25 },
    { club: 'Drama', events: 5, members: 20 },
  ],
  resourceUsage: [
    { resource: 'Auditorium', hours: 120 },
    { resource: 'Labs', hours: 200 },
    { resource: 'Seminar Halls', hours: 150 },
    { resource: 'Equipment', hours: 80 },
    { resource: 'Conference', hours: 60 },
  ],
  budgetOverview: [
    { category: 'Events', amount: 150000 },
    { category: 'Equipment', amount: 50000 },
    { category: 'Marketing', amount: 30000 },
    { category: 'Travel', amount: 25000 },
  ],
};
